# Generated by Django 3.2 on 2021-07-16 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlannedIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=120)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repetitive', models.BooleanField()),
                ('repeat_month', models.DateField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.period')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlannedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=120)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repetitive', models.BooleanField()),
                ('repeat_month', models.DateField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.period')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
