# Generated by Django 3.2 on 2021-10-04 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('in', 'income'), ('ex', 'expense')], default='ex', max_length=2)),
                ('repetitive', models.BooleanField()),
                ('repeat_month', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default='01', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.entry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='plannedincome',
            name='period',
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex=re.compile('\\d{4}-[0-1]\\d'))]),
        ),
        migrations.DeleteModel(
            name='PlannedExpense',
        ),
        migrations.DeleteModel(
            name='PlannedIncome',
        ),
        migrations.AddField(
            model_name='entry',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.period'),
        ),
    ]
