# Generated by Django 3.2 on 2021-07-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.DateField(unique=True),
        ),
    ]
